name: Trigger auto deployment for fbf-buddy-discord-bot

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/fbf-buddy-discord-bot-AutoDeployTrigger-3b850ea5-2d6e-4982-9ba7-62c6858f209e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v6

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.FBFBUDDYDISCORDBOT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FBFBUDDYDISCORDBOT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FBFBUDDYDISCORDBOT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/services/discord-bot
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: fbfregistry.azurecr.io
          registryUsername: ${{ secrets.FBFBUDDYDISCORDBOT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FBFBUDDYDISCORDBOT_REGISTRY_PASSWORD }}
          containerAppName: fbf-buddy-discord-bot
          resourceGroup: peter-corp-rg
          imageToBuild: fbfregistry.azurecr.io/fbf-buddy-discord-bot:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


